---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://elasticsearch:9200"]

monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: elastic
xpack.security.encryptionKey: Te6DNwDAzwbF8viNoMMGlkVPP0RR7suZ

# https://www.elastic.co/guide/en/kibana/8.4/alert-action-settings-kb.html#general-alert-action-settings
xpack.encryptedSavedObjects.encryptionKey: a2d71394b3bba358117d33d43cac2bc4
xpack.reporting.encryptionKey: b61fd57640b4af1a886a3a4fc87fada0
## Fleet
## https://www.elastic.co/guide/en/kibana/current/fleet-settings-kb.html
#
# xpack.fleet.agents.fleet_server.hosts: [ 'http://fleet-server:8220' ]
# xpack.fleet.agents.elasticsearch.hosts: [ 'http://elasticsearch:9200' ]

# xpack.fleet.packages:
#   - name: fleet_server
#     version: latest
#   - name: system
#     version: latest
#   - name: elastic_agent
#     version: latest

# xpack.fleet.agentPolicies:
#   - name: Fleet Server policy
#     id: fleet-server-policy
#     description: Fleet Server policy
#     monitoring_enabled:
#       - logs
#       - metrics
#     package_policies:
#       - name: fleet_server-1
#         package:
#           name: fleet_server
#       - name: system-1
#         package:
#           name: system
#       - name: elastic_agent-1
#         package:
#           name: elastic_agent